### ISSUE TITLE
Unknown error after last upgrade

### ISSUE THREAD

**Issue by gediminasel** [wakatime/atom-wakatime#108]
After the last upgrade, the plugin no longer works and on startup I get
```
[wakatime.js:621] Error: Command failed:
C:\Users\user\.wakatime\wakatime-cli-windows-amd64.exe --entity
C:\Users\user\Desktop\foo\bar.tex --plugin atom-wakatime/11.0.4
--write --lineno 113 --verbose --config
C:\Users\user\.wakatime.cfg --alternate-project project
```
I checked and `proc.exitCode` is `1`. `stderr` and `stdout` are empty. In `.wakatime.cfg` `cli_version = v1.7.4`

However, if I change `cli_version` to `v1.7.1` in `.wakatime.cfg`, everything works fine.

And `cli v1.7.4` is re-downloaded on every startup while `v1.7.1` just prints that it's `up to date`.

**Comment by nhend** [comment]
I am also experiencing this error with the same behavior in the dev console regarding 1.7.4 updates. Forcing 1.7.1 in .wakatime.cfg also fixed things for me.

**Comment by OreoDivision** [comment]
For me, forcing 1.7.1 does not work, in the `.wakatime.log` it shows ```{"caller":"/home/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/today/today.go:44","func":"Run","level":"fatal","message":"failed fetching summaries from api: failed to make request to \"https://api.wakatime.com/api/v1/users/current/summaries\": Get \"https://api.wakatime.com/api/v1/users/current/summaries?end=2021-06-13&start=2021-06-13\": x509: certificate signed by unknown authority","now":"2021-06-13T15:03:18-05:00","version":""}
{"caller":"/home/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:47","func":"Run","level":"fatal","message":"failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": x509: certificate signed by unknown authority","now":"2021-06-13T15:03:21-05:00","version":""}
{"caller":"/home/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:47","func":"Run","level":"fatal","message":"failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": x509: certificate signed by unknown authority","now":"2021-06-13T15:03:21-05:00","version":""}
{"caller":"/home/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/today/today.go:44","func":"Run","level":"fatal","message":"failed fetching summaries from api: failed to make request to \"https://api.wakatime.com/api/v1/users/current/summaries\": Get \"https://api.wakatime.com/api/v1/users/current/summaries?end=2021-06-13&start=2021-06-13\": x509: certificate signed by unknown authority","now":"2021-06-13T15:05:14-05:00","version":""}
{"caller":"/home/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:47","func":"Run","level":"fatal","message":"failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": x509: certificate signed by unknown authority","now":"2021-06-13T15:05:19-05:00","version":""}
```

**Comment by alanhamlett** [comment]
@OreoDivision that's a bug where our new Go version of wakatime-cli isn't working correctly with custom proxy MITM certs. We're working on fixing it with https://github.com/wakatime/wakatime-cli/issues/385, but for now you can get yours working by disabling SSL verification in your `~/.wakatime.cfg` file:

`no_ssl_verify = true`

**Comment by BestSithInEU** [comment]
> @OreoDivision that's a bug where our new Go version of wakatime-cli isn't working correctly with custom proxy MITM certs. We're working on fixing it with [wakatime/wakatime-cli#385](https://github.com/wakatime/wakatime-cli/issues/385), but for now you can get yours working by disabling SSL verification in your `~/.wakatime.cfg` file:
> 
> `no_ssl_verify = true`

This is not worked for me.

**Comment by OreoDivision** [comment]
> @OreoDivision that's a bug where our new Go version of wakatime-cli isn't working correctly with custom proxy MITM certs. We're working on fixing it with https://github.com/wakatime/wakatime-cli/issues/385, but for now you can get yours working by disabling SSL verification in your `~/.wakatime.cfg` file:
> 
> 
> 
> `no_ssl_verify = true`

I was able to fix it using a different issue

**Comment by OreoDivision** [comment]
> @OreoDivision that's a bug where our new Go version of wakatime-cli isn't working correctly with custom proxy MITM certs. We're working on fixing it with https://github.com/wakatime/wakatime-cli/issues/385, but for now you can get yours working by disabling SSL verification in your `~/.wakatime.cfg` file:
> 
> 
> 
> `no_ssl_verify = true`

Okay, that was the fix that I used

**Comment by alanhamlett** [comment]
@BestSithInEU @OreoDivision if you remove `no_ssl_verify = true` from `~/.wakatime.cfg` then restart Atom to get the latest wakatime-cli v1.18.9, does that also fix the issue for you?

**Comment by OreoDivision** [comment]
> @BestSithInEU @OreoDivision if you remove `no_ssl_verify = true` from `~/.wakatime.cfg` then restart Atom to get the latest wakatime-cli v1.18.9, does that also fix the issue for you?

sorry for the late response but that worked thanks
