### ISSUE TITLE
Unknown Error (1); Check your Dev Console and ~/.wakatime.log for more info

### ISSUE THREAD

**Issue by Invidam** [wakatime/atom-wakatime#109]
I installed wakatime in atom and entered api key and then I restarted atom.
When I code somethings, 'Error' appeared so I can't use wakatime services.
(In waka website, wakatime plugin status loading never ends )

+ I use atom 1.57.0 and windows 10 and wakatimes version is 11.0.4

+ So I installed in VScode. In this time, It has no errors.

+ there was similar error in   [https://github.com/wakatime/atom-wakatime/issues/88](url)

Dev console say this:
```
C:\Users\asas2\.atom\packages\wakatime\lib\logger.js:65 [WakaTime] [WARN] [wakatime.js:621] Error: Command failed: 
C:\Users\asas2\.wakatime\wakatime-cli-windows-amd64.exe --entity C:\Users\asas2\OneDrive\바탕 화면
\Programming\Projects\KakaoTalk_Clone_Coding\contents\index.html --plugin atom-wakatime/11.0.4 --lineno 7 --verbose --config 
C:\Users\asas2\.wakatime.cfg --alternate-project KakaoTalk_Clone_Coding
```

**Comment by alanhamlett** [comment]
It looks related to #108 and maybe https://github.com/wakatime/wakatime-cli/issues/432.

**Comment by Invidam** [comment]
Thank you I solved it!!
