### ISSUE TITLE
Does not work behind a proxy

### ISSUE THREAD

**Issue by npassaro** [wakatime/atom-wakatime#11]
Hi,

Wakatime does not seem to work behind a proxy, however atom is correctly configured to do so.

**Comment by alanhamlett** [comment]
Can you try adding the proxy to your `~/.wakatime.cfg` file:
https://github.com/wakatime/wakatime#configuring

**Comment by npassaro** [comment]
Thanks for the quick reply.

Ok, I did not see that config part in wakatime github, don't ask me why...

Is there a configuration option to ignore certificates?

**Comment by npassaro** [comment]
I was able to get around this validation putting this:
```
url = { url: 'https://github.com/wakatime/wakatime/archive/master.zip', strictSSL: false }
```
in [wakatime.coffe](https://github.com/wakatime/atom-wakatime/blob/master/lib/wakatime.coffee#L158)

This is not completely advisable but my the corporate proxy makes it hard to do in any other way.

It would be an interesting addition to the configuration option in atom.

*kudos for a easy to read code base :smile:*

**Comment by alanhamlett** [comment]
Just released this change in the latest version.
