### ISSUE TITLE
Startup time

### ISSUE THREAD

**Issue by ghost** [wakatime/atom-wakatime#112]
Why, is it  taking so long the start up time to finish?  I started with 34ms two days ago now today is at 15ms. Talking about: This package added 15ms to start up time.

**Comment by alanhamlett** [comment]
Maybe because it checks for updates to 2 wakatime-cli programs, as we're rolling out the new Go wakatime-cli we still need the legacy Python wakatime-cli to fallback when Go has any errors sending code stats.

**Comment by alanhamlett** [comment]
Should be faster now that we're using the GitHub API with etags.
