### ISSUE TITLE
Failed to send hearbeat(s)

### ISSUE THREAD

**Issue by Firearrow5235** [wakatime/atom-wakatime#113]
I'm getting the following error in the logs 

`{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp 68.183.248.166:443: connect: connection refused","now":"2021-08-31T16:36:23-04:00","version":"v1.19.0"}`

Only thing I've tried is updating my API key. Any ideas?

**Comment by ouatataz** [comment]
It looks related to #108 and maybe wakatime/wakatime-cli#432.

**Comment by alanhamlett** [comment]
Try restarting Atom and it should get the fixed wakatime-cli.

Fixed with wakatime/wakatime-cli#539.
