### ISSUE TITLE
extracting wakatime-cli... stucked ?

### ISSUE THREAD

**Issue by ouatataz** [wakatime/atom-wakatime#115]
I use Wakatime in Atom with my API key. Since about 2 days, in the status bar of Atom, it says extracting wakatime-cli... indefinitely. I'm not sure if heartbeats are sent or not...

I'm using Atom 1.58.0 on MacOS Catalina with Wakatime plugin 11.0.4 (no update available).

**Comment by alanhamlett** [comment]
Please turn on debug mode, re-launch Atom, then open your Dev console and paste any WakaTime related messages here.

https://github.com/wakatime/atom-wakatime#troubleshooting

**Comment by ouatataz** [comment]
It looks like it is working today.
Thank you for your kind answer.
