### ISSUE TITLE
Saving Files On Ubuntu 

### ISSUE THREAD

**Issue by ghost** [wakatime/atom-wakatime#117]
I've combed through some of the other issues and have tried reinstalling the plugin, using different versions of the wakatime python package, disabled the spell-check plugin, turned debug logging on and off, and I still have problems on Ubuntu whenever I save a file. Seems to lock up on every invocation of the python module for whatever reason.

I'm running Ubuntu 19.04 with Atom 1.40.1.
How can I run Ubuntu 19.04 with Atom 1.40.1?

**Comment by alanhamlett** [comment]
Turn on debug mode and see if there's any error messages in your Atom Dev console, or `~/.wakatime.log` file:
https://github.com/wakatime/atom-wakatime#troubleshooting

**Comment by alanhamlett** [comment]
Closing because we need more info to debug this.
