### ISSUE TITLE
Package installation failing

### ISSUE THREAD

**Issue by FEDbySandrine** [wakatime/atom-wakatime#124]
> Installing “wakatime@11.0.11” failed.Hide output…
> Package version: 11.0.11 not found

Atom v1.60.0 (latest)
macOs Montery v12.0.1

<img width="735" alt="Screen Shot 2022-05-14 at 8 52 46 am" src="https://user-images.githubusercontent.com/87841794/168388579-7007fa74-debf-4e2b-a148-ae1b4f4bbd72.png">

**Comment by alanhamlett** [comment]
This is due to a bug in Atom https://github.com/atom/atom/issues/25426

**Comment by alanhamlett** [comment]
To install atom-wakatime manually, run:

```
cd ~/.atom/packages
git clone git@github.com:wakatime/atom-wakatime.git
cd atom-wakatime
npm install
```

**Comment by Cristishor201** [comment]
> To install atom-wakatime manually, run:
> 
> ```
> cd ~/.atom/packages
> git clone https://github.com/wakatime/atom-wakatime.git
> cd atom-wakatime
> npm install
> ```

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 145 packages from 169 contributors and audited 146 packages in 17.901s
found 0 vulnerabilities
```
