### ISSUE TITLE
Error install wakatime on atom

### ISSUE THREAD

**Issue by Cristishor201** [wakatime/atom-wakatime#125]
I tried to install the plugin on atom 64bit on both Versions : _V1.50_ , _V1.60_

![image](https://user-images.githubusercontent.com/26629669/171947204-6b8d39db-6f27-4579-986b-7fa976c7198c.png)

**Comment by alanhamlett** [comment]
Duplicate of #124.

**Comment by alanhamlett** [comment]
Closing this issue since Atom is no longer supported. This plugin does work in [Pulsar](https://pulsar-edit.dev/) as an alternative to Atom.
