### ISSUE TITLE
Error SSL

### ISSUE THREAD

**Issue by rafaelstz** [wakatime/atom-wakatime#16]
{"now": "2015/06/12 12:36:08 +0000", "version": "4.0.14", "plugin": "atom-wakatime/4.0.9", "time": 1434123368.425476, "level": "WARNING", "message": "/home/rafael/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning\n"}

**Comment by alanhamlett** [comment]
This is because of an old version of Python. You can disregard the warning, or upgrade Python.

**Comment by rafaelstz** [comment]
Thanks! :+1:
