### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by saki007ster** [wakatime/atom-wakatime#17]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
<unknown> (/Users/saket/.atom/packages/wakatime/lib/wakatime.coffee:34:24)
```

**Comment by alanhamlett** [comment]
That usage was removed back in v4.0.0 of the plugin:
https://github.com/wakatime/atom-wakatime/blob/master/HISTORY.rst#400-2015-01-21
