### ISSUE TITLE
Incomplete installation on Atom 1.0

### ISSUE THREAD

**Issue by montogeek** [wakatime/atom-wakatime#18]
Hi!

After install the package via Atom, I get this message in the console:
![screen shot 2015-06-25 at 22 08 12](https://cloud.githubusercontent.com/assets/1002461/8369948/e27a9c78-1b86-11e5-8906-44cdc29632eb.png)
![screen shot 2015-06-25 at 22 08 06](https://cloud.githubusercontent.com/assets/1002461/8370074/c7f40342-1b88-11e5-81ef-f9b907868261.png)

Looks like Atom didn't unzip the file or this new version of Atom needs something else to do it.

**Comment by montogeek** [comment]
I reinstalled it, this time I go to the directory and runned `unzip wakatime-master.zip -d .` and now it works :)

**Comment by alanhamlett** [comment]
A bug was introduced in the last release, but it's fixed in v4.0.11 with 1557fc1b1dd97996cc9e24e35a08cb2aaebdeb90.

Thanks for finding this!

**Comment by montogeek** [comment]
Your welcome :)
