### ISSUE TITLE
Unable to install package behind proxy

### ISSUE THREAD

**Issue by albertosantini** [wakatime/atom-wakatime#19]
On Windows 8.0 box, Atom 1.0.

```
Installing “wakatime@4.0.11” failed.Hide output…

gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.
```

Python and compiler installed.
Python works correctly from the command prompt (path is ok).
io.js 2.3.1 is installed and works correctly from command prompt (path is ok).

Yesterday I installed the plugin on Windows 7 sp 1 64 bit with the same configuration and the installation was ok.

Any hint?

**Comment by albertosantini** [comment]
It seems I get the same error for any plugin.

Let me investigate.
I close the issue in a while.

**Comment by alanhamlett** [comment]
Looks like you have to set Atom to use the correct proxy:
https://github.com/atom/apm#behind-a-firewall

Found from atom/atom-package-downloader#1

I'll leave this issue open so others can find the solution.
