### ISSUE TITLE
cannot configure settings

### ISSUE THREAD

**Issue by BorelTung** [wakatime/atom-wakatime#22]
There is no 'Settings' button on the WakaTime Package
Atom version: 1.0.2
WakaTime version: 4.0.12

**Comment by alanhamlett** [comment]
This is fixed?

**Comment by BorelTung** [comment]
Yeah, it fixed, this setting can be found inside. Sorry for replying late.

**Comment by zeusent** [comment]
Sorry for posting on a closed issue, but I'm having a hard time finding the settings panel for Wakatime... can someone help me please?

Atom: 1.0.11
WakaTime: 4.0.17

**Comment by zeusent** [comment]
Oh! Never mind! All I had to do is click on that thing... What got me confused is that other plugins have a "Settings" button next to Uninstall... Anyway, thanks! :D
