### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by mihailov-vf** [wakatime/atom-wakatime#23]
The plugin don't have recognized the project name on Atom.
The spent time was registered on a Unknown Project.

**Comment by alanhamlett** [comment]
By project, you mean an atom [Project Directory](https://atom.io/docs/api/v1.0.4/Project#instance-getDirectories) from the `Add Project Folder` menu item?

**Comment by mihailov-vf** [comment]
Either by opening a folder or Add Project Folder results on register for an Unknown project.

**Comment by lordnynex** [comment]
This is only an issue for project directories that are not git repositories.

**Comment by lordnynex** [comment]
I think a good future improvement would be to check for the existence of a .wakafile in the project root. This has other interesting possibilities like overriding values in ~/.wakatime.cfg. This method could also lay the groundwork for tracking team activity on a per project basis.

**Comment by alanhamlett** [comment]
@lordnynex we already have some similar features with a `.wakatime-project` file in the project folder and by listing the folder in your `~/.wakatime.cfg` file under the `[projectmap]` config section:
https://github.com/wakatime/wakatime/blob/master/wakatime/projects/projectmap.py#L10

These features are just not well documented yet.

**Comment by codex8** [comment]
i have same problem wakatime don't recognize project name i tried with 3 different project all goes into unknown

**Comment by alanhamlett** [comment]
Fixed with v5.0.3
