### ISSUE TITLE
Phyton installation/uninstallation

### ISSUE THREAD

**Issue by rugk** [wakatime/atom-wakatime#24]
IMO it's not very nice that you install Phyton on Windows 7 without asking the user.
At the installation a Windows Installer window is shown (without prior saying this to the user) and installs Phyton (it even asks the user for permission with UAC). At least a kind of 'This package requires Phyton. It will be installed now. [OK] [Cancel]' would be nice.

Secondly when trying to uninstall the package it seems there is another python error
![wkatime_uninstallation](https://cloud.githubusercontent.com/assets/11966684/9387197/c4fe8cea-475f-11e5-944d-f160a373e80d.PNG)

And there is no way to uninstall this package without uninstalling Phyton. (for working around this error)

Atom 1.0.7

**Comment by alanhamlett** [comment]
0bf9f32bcf992144674b2ad40d1e3cff8dd9b6b5 prompts the user before installing Python and 86ec64efd5ffc997f6ce109d8de1ec0a7c1b0740 removes the `wakatime-master` directory when the wakatime package is uninstalled.

Can you try the new version just released?

**Comment by rugk** [comment]
Yes the new version works. Thanks for fixing this do quickly.
