### ISSUE TITLE
Uncaught Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by Bantes** [wakatime/atom-wakatime#25]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Unknown Windows Version
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package, v4.0.16

### Stack Trace

Uncaught Invalid or unsupported zip format. No END header found

```
At C:\Users\Administrator\.atom\packages\wakatime\node_modules\adm-zip\zipFile.js:66

undefined
```

### Commands

```
  3x -2:21.4.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "wakatime": {
    "ignore": [
      "^/var/",
      "^/tmp/",
      "^/private/",
      "COMMIT_EDITMSG$",
      "PULLREQ_EDITMSG$",
      "MERGE_MSG$"
    ],
    "apikey": "946276e3-bc14-486e-9eb4-f98e1d150544"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.7
color-picker, v2.0.11
docblockr, v0.7.3
emmet, v2.3.12
laravel, v0.7.0
minimap, v4.13.3
wakatime, v4.0.16

# Dev
No dev packages
```

**Comment by alanhamlett** [comment]
@Bantes thanks for submitting, however make sure to change your API Key since it's included in this issue publicly.

This bug should be fixed in v4.0.17.
