### ISSUE TITLE
store api key outside atom config file

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/atom-wakatime#26]
because submitting traceback automatically includes secret api key in public github issue.

**Comment by albertosantini** [comment]
and we cannot commit the settings to a public repo to sync the preferences.

**Comment by alanhamlett** [comment]
I was going to move the api key from atom config into `~/.wakatime.cfg`. Do you store your `~/.wakatime.cfg` file on a public repo?

**Comment by albertosantini** [comment]
No. dotfiles containing sensible info are not synced and it is a fair decision.

**Comment by alanhamlett** [comment]
Still need to prevent api keys from being stored in the Atom config file, even if it's read from `~/.wakatime.cfg` by default.

**Comment by albertosantini** [comment]
With `5.0.1` I removed api key from the atom settings, using the key stored in `~/.wakatime.cfg`.

For me it would be enough to add a text in the atom settings, warning the api key would be stored in atom config file.

Likely https://github.com/wakatime/atom-wakatime/blob/master/lib/wakatime.coffee#L28
```
Your secret key from https://wakatime.com/settings. Be aware, if filled, it is stored in config file.
```
