### ISSUE TITLE
Python installs on Windows, but asks again with every start

### ISSUE THREAD

**Issue by joerocklin** [wakatime/atom-wakatime#29]
On first install, I allowed the plugin to install Python. Python was installed to C:\Python34, but the plugin asks about installing again with every start of Atom.

**Comment by alanhamlett** [comment]
This probably means the installation was corrupted somehow. Do you see any errors when you type these two commands in a cmd prompt?

```
pythonw --version
\Python34\pythonw --version
```

**Comment by joerocklin** [comment]
@alanhamlett the first prints an error (not surprising as it's not in my path), the second prints nothing. However, `\Python34\python --version` does show v3.4.3.

**Comment by alanhamlett** [comment]
Is this fixed with v5.0.1?
