### ISSUE TITLE
Atom locks up when editing .info file

### ISSUE THREAD

**Issue by Cybnext** [wakatime/atom-wakatime#3]
It appears that the highlight.js integration is to blame. The problem lies with the highlight.highlightAuto method. It appears to just lock up the thread when it's given source that it can't determine what language it is.

I have a .info file that completely locks up Atom. However, after commenting out the highlightAuto() call, nothing locks up.

**Comment by alanhamlett** [comment]
This could be related to isagalaev/highlight.js#666

**Comment by alanhamlett** [comment]
Can you try re-installing the WakaTime plugin and see if the issue persists?

**Comment by Cybnext** [comment]
Fantastic! Everything appears to be working great now :)

**Comment by alanhamlett** [comment]
Awesome!
