### ISSUE TITLE
Wakatime stopped recording

### ISSUE THREAD

**Issue by lordnynex** [wakatime/atom-wakatime#30]
No idea what happened but I see ~/.wakatime.log has a lot of warnings about 

"WARNING", "message": "/home/lordnynex/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning\n"

Which shouldn't be fatal.

But the last line in the log says 
{"now": "2015/10/05 10:14:59 +0000", "version": "4.1.7", "plugin": "atom-wakatime/4.1.0", "time": 1444065299.251507, "level": "ERROR", "message": "Exception:"}

Which is 7 days old. Nothing since. Is there anything I can do to jump start this thing again? I'm a paying member.

**Comment by alanhamlett** [comment]
First, can you check for errors in your Dev Console with `View -> Developer -> Toggle Developer Tools`?

**Comment by lordnynex** [comment]
![wakatime-dev-console](https://cloud.githubusercontent.com/assets/1108594/10442327/05fd4fea-7106-11e5-82ea-ace92449483a.png)

Around this date, I changed my git project dir structure. I tend to launch atom from the console, and now launch it pointed at a dir that is a symlink. I also recently started using 'Add project to tree' instead of launching multiple atom windows.

**Comment by alanhamlett** [comment]
Can you try typing in a file and saving the changes, then looking for Console errors? The above errors are not related to wakatime, since they don't say `wakatime/lib/wakatime.coffee`.

**Comment by lordnynex** [comment]
@alanhamlett I have been by virtue of working. I just opened a repo, made a few changes, saved. Nothing in console.

**Comment by alanhamlett** [comment]
Did the wakatime package get uninstalled or disabled in your Atom?

You should see these wakatime init messages:
```
WakaTime v5.0.0 loaded.
Current wakatime-cli version is 4.1.8
Checking for updates to wakatime-cli...
wakatime-cli is up to date.
```

**Comment by lordnynex** [comment]
Nope. But looking at it in my installed packages looks very strange. 

![waka-installed](https://cloud.githubusercontent.com/assets/1108594/10442571/8edb9892-7108-11e5-973e-b5114358e3db.png)

**Comment by alanhamlett** [comment]
Can you try uninstalling and reinstalling wakatime?

**Comment by lordnynex** [comment]
OH! 

So I've been noticing for awhile that the plugin periodically updates itself with new wakatime-master in lib/. This is perhaps not a good design approach. In this case it's done so while the editor was running with elevated privileges. Weird that I happened to run the editor just happened to be running with elevated privileges when wakatime updated the lib. 

So this is not a normal use case for me (my fancy new mouse wasn't being detected by xorg so it was a bit of a hands free change to get it working). It does seem like it should be the users prerogative to run the editor with elevated privileges, however. 

```
-rw-rw-rw- 1 root      root       260 Sep 29 00:14 AUTHORS
-rw-rw-rw- 1 root      root       177 Oct  5 13:56 .coveragerc
-rw-rw-rw- 1 root      root       286 Sep 29 00:14 dev-requirements.txt
-rw-rw-rw- 1 root      root       330 Sep 29 00:14 .gitignore
-rw-rw-rw- 1 root      root      8.5K Sep 29 00:14 HISTORY.rst
-rw-rw-rw- 1 root      root      1.6K Sep 29 00:14 LICENSE
-rw-rw-rw- 1 root      root       111 Sep 29 00:14 MANIFEST.in
-rw-rw-rw- 1 root      root       16K Sep 29 00:14 NOTICE
-rw-rw-rw- 1 root      root      4.2K Sep 29 00:14 README.rst
-rw-rw-rw- 1 root      root       100 Sep 29 00:14 setup.cfg
-rw-rw-rw- 1 root      root      1005 Sep 29 00:14 setup.py
drwxr-xr-x 3 root      root      4.0K Sep 29 00:14 tests
-rw-rw-rw- 1 root      root       124 Sep 29 00:14 tox.ini
-rw-rw-rw- 1 root      root       482 Sep 29 00:14 .travis.yml
drwxr-xr-x 5 root      root      4.0K Sep 29 01:01 wakatime
```

**Comment by alanhamlett** [comment]
Ok, let's try deleting that `wakatime-master` folder and reinstalling the `wakatime` package then restart Atom without Admin privileges. The `wakatime` package should then re-download `wakatime-master` and you should see the init messages in the Console.

**Comment by lordnynex** [comment]
yea it's good. thanks for the help.

**Comment by alanhamlett** [comment]
Awesome! Glad you got it fixed :+1:
