### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/atom-wakatime#31]
> I get high cpu usage frequently and my macbook gets insanely hot. So I had to uninstall it for the time being.
> -@joliveros

Need to find the cause of high CPU usage and find how to reproduce it. Anyone else experiencing high cpu usage please feel free to comment.

**Comment by alanhamlett** [comment]
Anyone who is experiencing high cpu usage, which OS are you using? If you disable the built-in `spell-check` package does that fix it?

https://github.com/wakatime/atom-wakatime/issues/43#issuecomment-205449115

**Comment by alanhamlett** [comment]
Update: Could be caused by atom/atom#6437

**Comment by Nittarab** [comment]
![image](https://user-images.githubusercontent.com/6181406/29885213-569d3c7a-8db6-11e7-8114-11ce9462e469.png)
mmm what about that?

**Comment by matrixik** [comment]
I started getting this now. Wakatime is killing whole system... Disabled for now.
Ubuntu 18.04.01, Atom 1.33, Wakatime 7.0.7.

**Comment by gandarez** [comment]
No one else have been experiencing high cpu usage. Closing this issue, please feel free to reopen.
