### ISSUE TITLE
Custom project name

### ISSUE THREAD

**Issue by danielbrodin** [wakatime/atom-wakatime#32]
Is it possible to add a custom project name instead of using the folder name? For example I have a wordpress site where it's just the wp-content folder that is open in the editor which kinda makes it useless to track. There are times where I have also renamed a folder after some time, and it would be nice to keep tracking it on the same time.

**Comment by alanhamlett** [comment]
You can create a file `.wakatime-project` with the first line having the new project name. Put that file in your project folder and wakatime will use that project name instead of the folder name.

**Comment by danielbrodin** [comment]
Thanks. It worked great. Is there anything else that can be configured in the `.wakatime-project` file? Couldn't find anything on it.

**Comment by alanhamlett** [comment]
No, but you can configure things in your `~/.wakatime.cfg` INI file:
https://github.com/wakatime/wakatime#configuring

Including mapping directories to project names:
https://github.com/wakatime/wakatime/blob/master/wakatime/projects/projectmap.py#L10
