### ISSUE TITLE
console output

### ISSUE THREAD

**Issue by albertosantini** [wakatime/atom-wakatime#34]
I don't know the best practice for logging, but in the console I see the following output, when I start the editor:

```
WakaTime v5.0.0 loaded.
Current wakatime-cli version is 4.1.8
Checking for updates to wakatime-cli...
wakatime-cli is up to date.
```

Maybe using a message panel for the output and  a `debug` setting to control it would be a feasible approach.

**Comment by alanhamlett** [comment]
Fixed in v6.0.3 with a Debug checkbox in the wakatime package settings.
