### ISSUE TITLE
Slow upstart

### ISSUE THREAD

**Issue by kevinsimper** [wakatime/atom-wakatime#35]
It takes quite some time to start on my mac pro 15", newest version of atom.

![image](https://cloud.githubusercontent.com/assets/1126497/11275984/6fb2f1f4-8ee0-11e5-951d-8adf9855a51f.png)

A way to make it faster could be to only first require request and adm-zip when they are actually used.
https://github.com/wakatime/atom-wakatime/blob/master/lib/wakatime.coffee#L9-L16

**Comment by kevinsimper** [comment]
@alanhamlett I think this is a something that could be improved easily, because each package's `activate` function is called sync, calling the API each time to check if the api is the latest is not the correct thing to do. The api could be instead upgraded with an atom package.

![image](https://cloud.githubusercontent.com/assets/1126497/11440713/3a55e090-9505-11e5-9ecf-e1cecfdbe87f.png)

**Comment by alanhamlett** [comment]
34179e2b0b0412fb9dc27894769b1b802b43cb24 moves package loading into the activate method, but this doesn't seem to change the package startup time as reported in the package settings.

<img width="1437" alt="screen shot 2015-11-29 at 8 47 44 pm" src="https://cloud.githubusercontent.com/assets/522344/11462535/5766aafc-96db-11e5-9c74-aa544c36da03.png">

**Comment by kevinsimper** [comment]
@alanhamlett Yes, that does not make any difference, but if the `require('adm-zip')` happend here, it would be and improvement, since it is only used once.

I looked at it more and does the time come from the API call?

**Comment by Stephn-R** [comment]
What if we did a bit of code refactoring? I can take a look @alanhamlett

**Comment by alanhamlett** [comment]
@kevinsimper you're right, [this function](https://github.com/wakatime/atom-wakatime/blob/28b0561a63fafbe07edc89210a7b1cd2c7229381/lib/wakatime.coffee#L51) could take a while.

@Stephn-R could we use a setTimeout to check for Python and wakatime-cli without blocking Atom? Maybe Atom has something to help run async code in it's plugin api?

**Comment by kevinsimper** [comment]
@alanhamlett You could do something like that, but does it need to check every time atom is loaded?

I may load atom 20-30 times a day just because I launch new windows from the terminal by `atom .` and wakatime effectively calls its api every time.

**Comment by alanhamlett** [comment]
@kevinsimper previously we had to deploy a new version of each plugin to release new versions of the common core wakatime-cli, but we switched to auto-detecting the current wakatime-cli version to make things much easier and robust.

I've created #37 to track the once-per-day update check change.

**Comment by Stephn-R** [comment]
Do you guys know if atom offers us the option to manage a custom settings file for Wakatime? If so, we could mitigate the check there and prevent a request going out everytime while maintaining some threshold as @kevinsimper mentioned.

**Comment by alanhamlett** [comment]
We could add a new config key:

https://github.com/wakatime/atom-wakatime/blob/master/lib/wakatime.coffee#L27

https://atom.io/docs/v1.2.4/behind-atom-configuration-api

**Comment by Stephn-R** [comment]
Nice, so maybe we can add some config data to track things such as:

- Last Updated
- Heartbeat Threshold

With these two, we can stretch out when the heartbeats are sent and also determine initial load through the last updated timer

**Comment by alanhamlett** [comment]
Let's leave heartbeat threshold as-is because more granularity is never bad.

**Comment by intellix** [comment]
508ms here on a MBP

**Comment by alanhamlett** [comment]
Startup time will be improved with #37.

**Comment by alanhamlett** [comment]
Hows the startup time now that #37 has been fixed and released?

**Comment by artdevjs** [comment]
any updates on this issue? with the latest update, the startup time is incredibly slow
<img width="623" alt="screen shot 2016-12-26 at 8 40 30 pm" src="https://cloud.githubusercontent.com/assets/7567983/21485414/c3d9cdc6-cbab-11e6-9c95-6db20561c00b.png">

**Comment by alanhamlett** [comment]
@artdevjs is the startup time always slow if you restart Atom again?

**Comment by artdevjs** [comment]
@alanhamlett  after some experiments, the average activation time now around ~150-200 ms. It depends on the settings and the number of activated packages at startup. Complete reinstallation of the Atom significantly increase startup time.
As a solution at the moment, I found [package-switch](https://github.com/deprint/package-switch) , it makes possible to lazy-load some packages or even whole bundles, with auto enable/disable different sets of packages specific per project.

**Comment by alanhamlett** [comment]
Ok, then it's probably because atom-wakatime was checking for updates. That only happens once per day, which is why the startup time was back to normal after restarting Atom a second time.

**Comment by caarlos0** [comment]
First start:

![image](https://cloud.githubusercontent.com/assets/245435/25400408/d939a9fe-29c8-11e7-908c-d635a1f9c509.png)

Second start:

![image](https://cloud.githubusercontent.com/assets/245435/25400420/eb258976-29c8-11e7-8870-2746977c30d8.png)

**Comment by alanhamlett** [comment]
Startup improved from ~300ms to under 10ms with the v7.0.0 release on my machine.
