### ISSUE TITLE
Failed to activate package named 'wakatime' Error: Cannot find module 'highlight.js'

### ISSUE THREAD

**Issue by gepoch** [wakatime/atom-wakatime#4]
Wakatime appears to be relying on a module that isn't being installed properly.. The package.json specifies a git URL for highlight.js, ~~but it doesn't seem to get installed on an `npm install wakatime`~~ which is being installed correctly, but `require 'highlight.js'` doesn't import it in the actual module.

**Comment by alanhamlett** [comment]
Can you update to v3.0.1 of the plugin, then restart Atom?

This new version removes the dependency on `highlight.js`.

**Comment by gepoch** [comment]
The error is gone in 3.0.1!

However, I'm now seeing https://github.com/wakatime/atom-wakatime/issues/6 but it's work-around-able for the time being!

Thanks for the quick response :)
