### ISSUE TITLE
Setting for showing status bar for wakatime

### ISSUE THREAD

**Issue by hultberg** [wakatime/atom-wakatime#40]
Hello, after the last update (5.0.3 -> 5.0.4) I noticed a bulky status bar icon in the bottom of my editor. I thought "no big deal, I'll just disable it." But I did not find any setting for it so... can I haz setting?

The option could also just be to hide the label "Wakatime active", i.e. showing just the icon.

![screenshot from 2016-02-24 09 31 33](https://cloud.githubusercontent.com/assets/1257913/13279639/95b1bdd2-dad9-11e5-95ce-f36c74f66761.png)

**Comment by alanhamlett** [comment]
Fixed in v5.0.8. Thanks!

**Comment by hultberg** [comment]
Good enought for me :+1:
