### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by cassioscabral** [wakatime/atom-wakatime#41]
The screenshot is old and it would be better to have a updated one.

I took one and will be making the PR to insert it, the link will come from this issue but feel free to host it if necessary.

![wakatimeprint](https://cloud.githubusercontent.com/assets/2073557/13750295/9ffcb6de-e9e3-11e5-8473-5d764f2458ec.png)

**Comment by alanhamlett** [comment]
Fixed with b0dc40a863e169db1ed7c60ac7283654d29f3566.
