### ISSUE TITLE
Does it work with atom-beta?

### ISSUE THREAD

**Issue by cmmata** [wakatime/atom-wakatime#44]
Hello all,

I'm using Atom Beta 1.8.0~beta0-0.1.fc21 (Fedora Core 21) and installed last version of wakatime plugin, but looks like it's not working. I see how much time I'm spending at the terminal, and how much I'm using Netbeans (each with it's own plugin), but I don't see atom's time. I don't see any error in .wakatime.log or in atom's developer console, all seems to be working there.

I tried to uninstall and install again the plugin, but still not working. What can I try?

**Comment by alanhamlett** [comment]
Can you turn on debug mode in your `~/.wakatime.cfg` file then check your `.wakatime.log` file again?

**Comment by alanhamlett** [comment]
I've just tested and it works with Atom 1.8.0-beta1.

**Comment by cmmata** [comment]
Hi, sorry for this very late reply.

I have been testing it today, and I don't know if it's because of a newer version of atom / atom-plugin, but now I see it's working.

Anyway, I have been using debug mode, and I see some messages like this one:
{"now": "2016/04/25 11:15:50 +0000", "version": "5.0.1", "plugin": "atom-wakatime/5.0.8", "time": 1461575689.828543, "caller": "/home/carlosmasip/.atom/packages/wakatime/lib/wakatime-master/wakatime/main.py", "lineno": 384, "isWrite": true, "file": "/home/carlosmasip/proyectos/sistemas/src/AppBundle/Command/EcommerceCommand.php", "level": "WARNING", "message": {"traceback": "Traceback (most recent call last):\n  File \"/home/carlosmasip/.atom/packages/wakatime/lib/wakatime-master/wakatime/main.py\", line 373, in send_heartbeat\n    proxies=proxies, timeout=timeout)\n  File \"/home/carlosmasip/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/sessions.py\", line 511, in post\n    return self.request('POST', url, data=data, json=json, **kwargs)\n  File \"/home/carlosmasip/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/sessions.py\", line 468, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/home/carlosmasip/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/sessions.py\", line 578, in send\n    r = adapter.send(request, **kwargs)\n  File \"/home/carlosmasip/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/adapters.py\", line 432, in send\n    raise ConnectTimeout(e, request=request)\nConnectTimeout: HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/heartbeats (Caused by ConnectTimeoutError(<wakatime.packages.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0272f311d0>, 'Connection to api.wakatime.com timed out. (connect timeout=60)'))\n", "ConnectTimeout": "HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/heartbeats (Caused by ConnectTimeoutError(<wakatime.packages.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0272f311d0>, 'Connection to api.wakatime.com timed out. (connect timeout=60)'))"}}

I can see logged time in Wakatime, so it's not failing each time. What can it be? I'm behind a firewall, but if it's a firewall problem, each api call should fail and I couldn't see any logged time. Am I right?

**Comment by alanhamlett** [comment]
That timeout happens sometimes when our api SSL endpoint has heavy load, but the plugin caches those heartbeats and tries uploading them every time a new heartbeat is created so everything is working.

**Comment by cmmata** [comment]
Ok, thank you. :+1:
