### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by montogeek** [wakatime/atom-wakatime#45]
I am getting this error since yesterday in the Atom Dev Console:

```
/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/montogeek/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py': [Errno 2] No such file or directory
```

I uninstalled it, installed it again but the error persists :(

This is the content of that folder:
```
montogeek ~/.atom/packages/wakatime/lib [12:44 PM]→ 😛
👉  ls
total 40
drwxr-xr-x   6 montogeek  staff   204B Apr 20 12:41 .
drwxr-xr-x  10 montogeek  staff   340B Apr 20 12:36 ..
-rw-r--r--   1 montogeek  staff   1.6K Apr 20 12:36 icon.png
-rw-r--r--   1 montogeek  staff   1.1K Apr 20 12:36 status-bar-tile-view.coffee
drwxr-xr-x  17 montogeek  staff   578B Apr 20 12:41 wakatime-master
-rw-r--r--   1 montogeek  staff    12K Apr 20 12:36 wakatime.coffee
```

Atom 1.7.2
OSX The Capitan upgraded from Yosemite

**Comment by montogeek** [comment]
Looks like a post installation command is failing :/

**Comment by alanhamlett** [comment]
That `wakatime-master/wakatime/cli.py` gets downloaded from GitHub when Atom starts, so does it get fixed after restarting Atom?

**Comment by montogeek** [comment]
@alanhamlett Is now sending heartbeats, but the file still does not exist. Weird, it broke after upgrade to The Capitan

**Comment by alanhamlett** [comment]
Yes, seems to be receiving heartbeats from Atom under your account. Did restarting Atom fix it?

**Comment by montogeek** [comment]
It looks like :)
