### ISSUE TITLE
wakatime API code for Atom text editor

### ISSUE THREAD

**Issue by erdemalpkaya** [wakatime/atom-wakatime#46]
hey everyone,

I got my API code but I'm not sure I put correct place! 
Do we have to put in:
Atom config
packets
wakatime
lib
wakatime.coffe

....
"
StatusBarTileView = require './status-bar-tile-view'

module.exports =
  config:
    apikey:
      title: '3b9de0d0-27a8-4190-9e82-7cf9146b3a7e'
      description: 'Your secret key from https://wakatime.com/settings.'
      type: 'string'
      default: ''
      order: 1
    ignore:

....

is it true??
if yes why still not working? 
Thank you for any response.
happy coding..

**Comment by alanhamlett** [comment]
No, you should go to Atom -> Packages -> wakatime -> Settings and put your api key in the input there.

Also, you just posted your secret api key publicly so please go to https://wakatime.com/settings/account and generate a new key ASAP!
