### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 66791: invalid start byte

### ISSUE THREAD

**Issue by thomassross** [wakatime/atom-wakatime#52]
From the log:

    {"now": "2015/12/14 16:48:05 +0000", "version": "4.1.8", "plugin": "atom-wakatime/5.0.1", "time": 1450129685.390131, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/home/thomas/.atom/packages/wakatime/lib/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/usr/lib/python2.7/codecs.py\", line 686, in read\n    return self.reader.read(size)\n  File \"/usr/lib/python2.7/codecs.py\", line 492, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 66791: invalid start byte\n"}

**Comment by alanhamlett** [comment]
Please first update to the latest version of the plugin, restart Atom, then check if the error is fixed.

**Comment by thomassross** [comment]
Hi,

I am on the latest version (5.0.8). It seems that the error in the log was not actually causing this error (I should've looked at the `now` entry haha). I restarted Atom and checked the developer console (it was downloading wakatime-cli), restarted Atom again and it seems to have fixed itself.

**Comment by alanhamlett** [comment]
Awesome!
