### ISSUE TITLE
Time tracking problem

### ISSUE THREAD

**Issue by ShavidzeT** [wakatime/atom-wakatime#53]
Wakatime doesn't tracking time when I work in Atom Editor.
Today I installed atom editor first time and in my dashboard on wakatime showed up atom in editors list, but doesn't tracking time.
How can we solve this problem, I don't know where is the problem, because I have already entered API key...

**Comment by alanhamlett** [comment]
Have you restarted Atom after installing WakaTime?

**Comment by ShavidzeT** [comment]
Sure, I have. BUT PROBLEM IS SAME

**Comment by alanhamlett** [comment]
Does Atom's `last_seen_at` value correspond to the last time you were coding in Atom:
https://wakatime.com/api/v1/users/current/user_agents

Edit a file in Atom, then check if the `last_seen_at` time updates.

**Comment by ShavidzeT** [comment]
Hey @alanhamlett, thank you for your response but problem is same.
I am new member inside aTom, I like it but need also wakatime, otherwise I'll back in sublime text :disappointed:

**Comment by alanhamlett** [comment]
What is your `last_seen_at` time from that URL above? From my end it looks like Atom was last seen 3 hours ago. Is the time reported not matching the actual time you worked, because we are receiving coding activity from Atom for you.

**Comment by neonbones** [comment]
Same here. `last_seen_at ` works fine, I can see my last connect, but wakatime doesn't tracking time and I have always `initializing` and then `error` in status bar. It's started after 6.0.0 update. 

devtools log
![error1](http://puu.sh/pcLYb/ae9b551283.png)
![error2](http://puu.sh/pcLZd/5f9bdfa866.png)

**Comment by alanhamlett** [comment]
@neonbones is there an error message in your `.wakatime.cfg` file in your User home folder?

**Comment by neonbones** [comment]
Nope, no errors, and everything works now, dunno what happened.

**Comment by ShavidzeT** [comment]
I removed wakatime package from sublime text and now works great.

**Comment by alanhamlett** [comment]
You mean Atom? The Sublime Text plugin and Atom plugin shouldn't effect each other at all.

**Comment by ShavidzeT** [comment]
Dunno, when I removed wakatime from sublime I reinstall package ib atam and
time was started tracking

**Comment by alanhamlett** [comment]
It was probably fixed by reinstalling the plugin in Atom, not uninstalling the plugin in ST.

**Comment by ShavidzeT** [comment]
@alanhamlett I had reinstalled wakatime in atom before this action, but problem was same, I want to have a time to write documentation about this problem, also I want to test it and solve. But genrally in my case, we don't know what was wrong, but I hope some problem will be fixed.
Great editor and great package :+1:
