### ISSUE TITLE
`Error: Command failed` on edit.

### ISSUE THREAD

**Issue by gepoch** [wakatime/atom-wakatime#6]
My dashboard isn't receiving updates under 3.0.1. I'm seeing this error pop up in the chromium logs:
```
Error: Command failed: python [...]/wakatime/lib/wakatime-master/wakatime-cli.py --file [...]/test.py --plugin atom-wakatime/3.0.1 usage: wakatime-cli.py [-h] --file file [--time time] [--write] [--plugin PLUGIN] [--project PROJECT_NAME] [--key KEY] [--disableoffline] [--hidefilenames] [--ignore IGNORE] [--logfile LOGFILE] [--config CONFIG] [--verbose] [--version] wakatime-cli.py: error: Missing api key
```

Following my nose, I found a good workaround, though! If you create a ~/.wakatime.cfg file with the following contents:
```
[settings]
api_key = <your_api_key_here!>
```

Everything works great!! :+1: 

But it looks like the atom config value for the API key isn't getting used.

**Comment by alanhamlett** [comment]
Oops, just fixed this in v3.0.2

**Comment by gepoch** [comment]
Perfect! All working now. You da man!

**Comment by alanhamlett** [comment]
:+1: You made it a lot easier by figuring out the fix. Thanks!
