### ISSUE TITLE
project not detected

### ISSUE THREAD

**Issue by stagfoo** [wakatime/atom-wakatime#62]
So i have been using this on sublime and it works great but how do i define a project for wakatime in atom? its either not coming up or showing unknown project which is straight because it has the git.

**Comment by alanhamlett** [comment]
Use revision control like Git, or open a folder as a project. More info here:

https://wakatime.com/faq#set-project-name

**Comment by stagfoo** [comment]
I am using git and atom is picking up the git but the time is not showing under that project even using custom rules, maybe its not sending to wakatime?

**Comment by alanhamlett** [comment]
Atom just passes the file to wakatime-cli, same as Sublime, so as long as the file is in a folder tracked by Git then the project will be detected.

Atom should send an alternate project from the current "Project Directory" if you've opened a folder listed in the sidebar. Have you opened a project folder or edited a file inside a folder tracked by Git?
