### ISSUE TITLE
Ubuntu 16.04.1 LTS + Atom not working

### ISSUE THREAD

**Issue by dieisonbeck** [wakatime/atom-wakatime#67]
Wakatime is not sending data through the plugin. I'm using the Ubuntu 16+ Atom version. It does not generate any .wakatim.log.
I already reinstalled the Atom and the plugin.
The only information generated is this image.

![captura de tela de 2016-12-13 20-38-11](https://cloud.githubusercontent.com/assets/23444155/21162478/aa68c1a8-c174-11e6-97d8-758e9a8f4469.png)

**Comment by alanhamlett** [comment]
In debug mode you should see some log messages in your Atom Console about sending heartbeats to the api, with the arguments being sent to wakatime-cli. If you code in some file do you see those messages?

**Comment by dieisonbeck** [comment]
Do not display any information on the console beyond the image above.
And the wakatime icon gets the message: "Wakatime ready"

**Comment by alanhamlett** [comment]
Have you typed some code in a file opened in Atom?

**Comment by dieisonbeck** [comment]
Yes and also created a new file.

**Comment by alanhamlett** [comment]
Any other plugins installed besides WakaTime?

**Comment by dieisonbeck** [comment]
![captura de tela de 2016-12-14 09-54-59](https://cloud.githubusercontent.com/assets/23444155/21181108/6fa63e0a-c1e3-11e6-8539-99c43b7ffdb6.png)

**Comment by dieisonbeck** [comment]
Running the following command, generated log.

python /home/dieison/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py --file /var/www/html/gsi/test/index.php --verbose --logfile .wakatime.log

{"now": "2016/12/16 02:06:03 +0000", "version": "6.2.0", "time": 1481861163.502778, "caller": "/home/dieison/.atom/packages/wakatime/lib/wakatime-master/wakatime/main.py", "lineno": 332, "file": "/var/www/html/gsi/test/index.php", "level": "DEBUG", "message": "Sending heartbeat to api at https://api.wakatime.com/api/v1/heartbeats"}

**Comment by dieisonbeck** [comment]
I discovered the problem.
He was on leave for the briefcase.
My project was in / var / www, so I switched to / home / user and ran normally.

**Comment by alanhamlett** [comment]
The problem was related to file permissions?

**Comment by dieisonbeck** [comment]
Yes

Em 16 de dez de 2016 10:31, "Alan Hamlett" <notifications@github.com>
escreveu:

**Comment by alanhamlett** [comment]
76bab463717e14d7f8cd75222d3d2f032c35b1c2 adds a note to the README about ignored file paths.
