### ISSUE TITLE
Ignoring /var/www/ directory

### ISSUE THREAD

**Issue by CaddyDz** [wakatime/atom-wakatime#68]
OS : **Debian Linux** (root)  
Latest **WakaTime** and **Atom** versions  
I think that the screenshot sums up my issue  
It works fine on **VS Code** though but I prefer **Atom**    
<img src="https://i.imgur.com/MgLLthu.png" alt="Screenshot" height="70" >  
PS: I know it does work outside /var directory but I want to keep it there 👍

**Comment by alanhamlett** [comment]
Fixed in v6.0.12.
