### ISSUE TITLE
Input API numer

### ISSUE THREAD

**Issue by joshuavickstrom** [wakatime/atom-wakatime#74]
Hello - sorry if the solution is simple, but I cannot input my API number. Instead there is just a link to the number on wakatime. I'm unsure if the setup is complete or this will be a problem. Please advise. 

Thanks!!!

**Comment by alanhamlett** [comment]
Can you paste the key into the input box where it says `Saved in your ~/.wakatime.cfg file`?

<img width="550" alt="screen shot 2017-05-15" src="https://cloud.githubusercontent.com/assets/522344/26063681/8c6a96a8-3943-11e7-9158-f400b5b3e25b.png">

You can always double check if the api key is saved in your `~/.wakatime.cfg` file located in your user home directory.

**Comment by joshuavickstrom** [comment]
Hi Alan - Thanks! Embarrassingly, I didn't even notice the space below for input. 😂

It worked! Take care!
