### ISSUE TITLE
wakatime offline, coding activity will sync when wakatime is online

### ISSUE THREAD

**Issue by shikhar-scs** [wakatime/atom-wakatime#76]
I am facing this problem on ATOM text editor. This message (wakatime offline, coding activity will sync when wakatime is online) keeps showing up even after the laptop is connected to the internet. As a result of this my wakatime dashboard is not getting updated since the last 4-5 days.

**Comment by alanhamlett** [comment]
What's the longer error message from your Atom Console Window, or `~/.wakatime.log` file in your user home folder?

**Comment by shikhar-scs** [comment]
where can i find the console window ? I'm using ubuntu so could  u please guide me through the path

**Comment by alanhamlett** [comment]
`ctrl-shift-I` opens your Atom Developer Console.

**Comment by dalvarezsmiet** [comment]
I have same issue, but with VSCode. The .wakatime.log is empty (0 KB) but there's a .wakatime.db with 40KB.

Any ideas?

**Comment by shikhar-scs** [comment]
One issue might be that you are misaing Python or using Ubuntu 17.10.

**Comment by crioto** [comment]
Same as @dalvarezsmiet 
Running vscode on arch linux.

**Comment by dalvarezsmiet** [comment]
Windows 10, VSCode 1.20.1
Python is not installed locally. What version should I choose, in case in have to install it?

**Comment by dalvarezsmiet** [comment]
SOLVED, I realized that wakatime plugin uses version snippets to accomodate to version 2 and 3, so I just went ahead and instaled latest one. It's now working fine.

**Comment by razorMureithi** [comment]
in arch it does not sync when i go back online

**Comment by alanhamlett** [comment]
@razorMureithi are there any error messages in your Dev Console window?

**Comment by nicholasinatel** [comment]
There is in mine, i am trying to run wakatime in atom now, could not get it with visual studio code.

`<embedded>:14 Cannot find module '..\build\Release\pty.node'
(anonymous) @ <embedded>:14
`
