### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by djh1997** [wakatime/atom-wakatime#77]
```
[WakaTime] [WARN] [wakatime.coffee:510] Error: Command failed: python /home/jo/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py --file /home/jo/Documents/uni/year 3/proj324/initial ideas.md --plugin atom-wakatime/7.0.3 --lineno 35 --verbose --no-ssl-verify --config /home/jo/.wakatime.cfg --alternate-project proj324
Traceback (most recent call last):
  File "/home/jo/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py", line 31, in <module>
    import wakatime
  File "/home/jo/.atom/packages/wakatime/lib/wakatime-master/wakatime/__init__.py", line 17, in <module>
    from .main import execute
  File "/home/jo/.atom/packages/wakatime/lib/wakatime-master/wakatime/main.py", line 15, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

dev console output

**Comment by djh1997** [comment]
reinstall didnt fix

**Comment by alanhamlett** [comment]
What happens when you type this in Terminal:

`python -c "import logging"`

**Comment by djh1997** [comment]
in gnome terminal i get nothing but dev console gives me `Uncaught SyntaxError: Unexpected string`

**Comment by alanhamlett** [comment]
Do you have multiple Python installations on your machine? The above line should have printed an `ImportError` from Terminal (shell not Atom console) unless WakaTime is using a different Python installation than when running Python from Terminal.

WakaTime tries to detect Python from your PATH env variable first as `pythonw`, then `python`. Next it tries running Python from '/usr/local/bin/python', then '/usr/bin/python'. Let's try the Terminal command again with a 'w' at the end this time:

`pythonw -c "import logging"`

Also, can you show the output of these Terminal commands:
* `which pythonw`
* `pythonw --version`
* `which python`
* `python --version`
* `/usr/local/bin/python --version`
* `/usr/bin/python --version`

**Comment by djh1997** [comment]
sorry for the slow reply 
![screenshot from 2017-11-10 12-32-31](https://user-images.githubusercontent.com/8309793/32658756-6baa1cb0-c613-11e7-8327-7154eb6683d7.png)
these are the results from the comands

**Comment by alanhamlett** [comment]
Can you try updating your Atom WakaTime plugin to v7.0.4 and see if it's fixed?

**Comment by djh1997** [comment]
yep all fixed now thanks :) love this plugin

**Comment by MubarakElrayah92** [comment]
@alanhamlett 
i'm facing the same issue kindly review my output below.

![image](https://user-images.githubusercontent.com/29518643/36719000-d6a74be0-1bb4-11e8-9b91-b911ae837903.png)

**Comment by alanhamlett** [comment]
@MubarakElrayah92 can you install Python3 with:

`brew install python`

If you don't already have Homebrew installed, you can install it with:

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by thinkycx** [comment]
Hello, everybody! I have melt with this problem and fix it by using the macOS system /usr/bin/python version 2.7.10 . Please should not use /usr/local/bin/python version 2.7.14  which is installed by brew.
You can change the python by `export PATH=/usr/bin:$PATH` .

I don't know why this works. If anybody knows, please tell me. Thank you very much.
@alanhamlett @djh1997 @MubarakElrayah92 @burka @e-jigsaw 

> @alanhamlett
> I facing the same issue kindly review my output below.
> 
> ![image](https://user-images.githubusercontent.com/29518643/36719000-d6a74be0-1bb4-11e8-9b91-b911ae837903.png)
> **I need your assistance to fix this issue here please, and kindly can you tell me about the root cause for this error up here?**

Hello, everybody! I have melt with this problem and fix it by using the macOS system /usr/bin/python version 2.7.10 . Please should not use /usr/local/bin/python version 2.7.14  which is installed by brew.
You can change the python by `export PATH=/usr/bin:$PATH` .

I don't know why this works. If anybody knows, please tell me. Thank you very much.
@alanhamlett @djh1997 @MubarakElrayah92 @burka @e-jigsaw
