### ISSUE TITLE
wakatime blocking?

### ISSUE THREAD

**Issue by maxim-lian** [wakatime/atom-wakatime#82]
While tests are running (and changing the file system), I'm getting a lot of jank in Atom. I recorded the events in Dev Tools, and found many of the long-running (500ms) calls were from Wakatime:

![image](https://user-images.githubusercontent.com/5635139/37319578-1a293478-2646-11e8-8279-3d9dceb5f605.png)

Is this something to do with the wakatime plugin blocking? Or wakatime happens to wrap a long running atom call?

Thanks!

**Comment by maxim-lian** [comment]
On disabling wakatime and restarting, I couldn't experience the jank, nor did it show in the console...

**Comment by alanhamlett** [comment]
Which tests are you running? WakaTime forks a process but doesn't block on that process, whenever these Atom events fire:

* [TextBuffer.onDidChange](https://atom.io/docs/api/v1.2.0/TextBuffer#instance-onDidChange)
* [TextBuffer.onDidSave](https://atom.io/docs/api/v1.2.0/TextBuffer#instance-onDidSave)
* [TextEditor.onDidChangeCursorPosition](https://atom.io/docs/api/v1.9.3/TextEditor#instance-onDidChangeCursorPosition)

If running tests through Atom causes those events to fire, try turning on Debug Mode in the WakaTime plugin in Atom's preferences. Then watch your Atom Dev Console and every time WakaTime forks a background process you will see a console log message.

**Comment by maxim-lian** [comment]
Thanks for the fast response!

Very weirdly, after re-enabling wakatime and turning on logging, the problem goes away. I'll leave it enabled and reopen this is the problem returns.
