### ISSUE TITLE
Confused UI in settings

### ISSUE THREAD

**Issue by JohnTitor** [wakatime/atom-wakatime#86]
I love waketime, thank you.
Using Atom, I became confused in settings.
I set Api Key, but the default message was shown instead of my Key. I thought something might be wrong, so I checked cfg file. It was fine.
I expected my Api Key was shown. I believe this would be best.
How do you think?

**Comment by codinggirl** [comment]
I think a better way is:

- The API Key text field shows `[Hidden]` when the key is set or `[Not Set]` when it runs first time.
- Add a comment line below the text field, shows `Location: $WAKATIME_HOME/.wakatime.cfg`.

If this is a acceptance way or has a similar way, I would make a PR.

**Comment by alanhamlett** [comment]
This is a great idea. Go for it! Thank you.
