### ISSUE TITLE
Invalid python version

### ISSUE THREAD

**Issue by s0kil** [wakatime/atom-wakatime#93]
Getting an error when installing the plugin:
```
Looking for python at: \python27\pythonw
Invalid python version: 
```

But I do have python 2.7 installed:
```
$ python --version
Python 2.7.17rc1
```

**Comment by alanhamlett** [comment]
What's the output of `which pythonw`?

That `Invalid python version` is a debug message, turn off debug mode and everything will work fine. It's finding Python just not at that specific location.

**Comment by tkroo** [comment]
in wakatime.coffee
```
re = /python\s+(\d+)\.(\d+)\.(\d+)\s/gi
ver = re.exec(versionString)
```
the above regular expression doesn't seem to handle version strings with 'rcX' in them. I hacked this:
`ver = re.exec(versionString.replace('rc1',''))`
and wakatime now works for me.
I know it would be better to fix the regular expression.

**Comment by s0kil** [comment]
@alanhamlett 
Here is the message I get after installing wakatime package and relaunching atom as requested by the plugin:
![Screenshot from 2019-11-05 14-53-36](https://user-images.githubusercontent.com/24403355/68241525-d4d30d00-ffdc-11e9-825c-07f97d223f26.png)

If I press OK, wakatime just says Initializing forever.

**Comment by s0kil** [comment]
@tkroo Thank You, That worked.

**Comment by tkroo** [comment]
:) There's a pull request to fix this problem here: https://github.com/wakatime/atom-wakatime/pull/91
