### ISSUE TITLE
Wakatime error as of latest update 8.0.2

### ISSUE THREAD

**Issue by TangSteven** [wakatime/atom-wakatime#96]
[WakaTime] [WARN] [wakatime.coffee:415] Error: spawn C:\Users\Steven\.atom\packages\wakatime\lib\wakatime-cli ENOENT

**Comment by alanhamlett** [comment]
Fixed with 7d55831cbafdf61a6d566c0cb22987c60495a98e, released in v8.0.3.

**Comment by TangSteven** [comment]
Still not working 8.0.3

**Comment by alanhamlett** [comment]
Fixed in v8.0.6 by correctly detecting Windows platform.

**Comment by TangSteven** [comment]
Thank you!
